# Generated by Django 3.0.3 on 2020-03-06 06:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200306_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, default='default/default-image.jpeg', upload_to=blog.models.Post.user_directory_path),
        ),
    ]
